_target_: anything_counter.anything_counter.anything_counter.AnythingCounter
defaults:
  - loader: video_loader
  - detector: openvino_detector
  - tracker: sort_tracker
  - counter: dummy
  - visualizer: opencv_visualizer